```{r cuminchfhosp, fig.cap="CI (consistency) 1 HF hospitalization"}
fit <- cuminc(matchp$sos_outtime_hosphf, 
              matchp$sos_out_hosphf_comp, 
              group = matchp$shf_bbl, 
              cencode = 0)

par(mar=c(4, 4, 1, 1) + 0.1)
plot(fit$`No 1`$time, fit$`No 1`$est, 
     ylab = "Cumulative incidence first HF hospitalization (%)",
     col = kicols[1], 
     xlim = c(0, 7 * 365.25),
     ylim = c(0, 1),
     xlab = "Years",
     type = "l",
     axes = F, 
     lwd = 3, 
     lty = 1 
)
matplot(fit$`Yes 1`$time, fit$`Yes 1`$est, 
        add = TRUE,
        col = kicols[2], 
        type = "l",
        lwd = 3, 
        lty = 2
)


axis(2, seq(0, 1, 0.25), seq(0, 100, 25), las = 2)
axis(1, at = seq(0, 7, 1) * 365, seq(0, 7, 1))

text(6 * 365, c(.45, .27), c("No bbl", "Bbl"), pos = 4)

```

```{r cuminccvd, fig.cap="CI (consistency) CVD"}
fit <- cuminc(matchp$sos_outtime_death, 
              matchp$sos_out_deathcv_comp, 
              group = matchp$shf_bbl, 
              cencode = 0)

par(mar=c(4, 4, 1, 1) + 0.1)
plot(fit$`No 1`$time, fit$`No 1`$est, 
     ylab = "Cumulative incidence first CVD (%)",
     col = kicols[1], 
     xlim = c(0, 7 * 365.25),
     ylim = c(0, 1),
     xlab = "Years",
     type = "l",
     axes = F, 
     lwd = 3, 
     lty = 1 
)
matplot(fit$`Yes 1`$time, fit$`Yes 1`$est, 
        add = TRUE,
        col = kicols[2], 
        type = "l",
        lwd = 3, 
        lty = 2
)


axis(2, seq(0, 1, 0.25), seq(0, 100, 25), las = 2)
axis(1, at = seq(0, 7, 1) * 365, seq(0, 7, 1))

text(6 * 365, c(.45, .27), c("No bbl", "Bbl"), pos = 4)
```