```{r spline, fig.cap="Association between EF and 1HF hospitalization - Quick and dirty"}

# form <- formula(paste0("Surv(sos_outtime_hosphf, sos_out_hosphf == 'Yes') ~ ns(shf_efproc, df = 4) + ",
#                                 paste(modvarspartialns, collapse = " + ")))
#     mod_yes <- coxph(form,
#       data = pdata %>% filter(shf_bbl == "Yes", !is.na(shf_efproc))
#     )
#     mod_no <- coxph(form,
#       data = pdata %>% filter(shf_bbl == "No", !is.na(shf_efproc))
#     )
#
mod_yes <- coxph(Surv(sos_outtime_hosphf, sos_out_hosphf == "Yes") ~ ns(shf_efproc, df = 4) +
  shf_age + shf_sex + sos_com_mi + sos_com_pci + sos_com_cabg + sos_com_af + sos_com_copd + sos_com_hypertension,
data = pdata %>% filter(shf_bbl == "Yes", !is.na(shf_efproc))
)
mod_no <- coxph(Surv(sos_outtime_hosphf, sos_out_hosphf == "No") ~ ns(shf_efproc, df = 4) +
  shf_age + shf_sex + sos_com_mi + sos_com_pci + sos_com_cabg + sos_com_af + sos_com_copd + sos_com_hypertension,
data = pdata %>% filter(shf_bbl == "Yes", !is.na(shf_efproc))
)

Greg::plotHR(list(mod_no, mod_yes),
  term = "shf_efproc", plot.bty = "o", xlim = c(50, 80),
  se = TRUE,
  polygon_ci = T,
  rug = "ticks",
  xlab = "EF",
  col.term = kicols[1:2],
  col.se = kicols[3:4]
)
```

This plot is performed on the whole cohort (so not the matched cohort). As previously wrote, ef is continuous in THEORY, however not really in practice. there are very few values. CI are enormous. I think perhaps skip analyses on continous EF....? 
```{r splineinfotab}
table(pdata$shf_bbl, pdata$shf_efproc)
```
